### ISSUE TITLE
Add support for NSNotification addObserver

### ISSUE THREAD

**Issue by AndrewSB** [wircho/Curly#3]
Not sure if this is the library, but adding support for NSNotification would be awesome!

**Comment by wircho** [comment]
I made a nice function which I often use to listen for notifications: `listen("SomeNotificationName") { note in ... }`. I will clean it up and add it to Curly when I find some time. Thanks again!

**Comment by AndrewSB** [comment]
Yup, I usually do the same thing in most of my projects too, would love to transition to just using curly!

**Comment by wircho** [comment]
I've added support for notifications. Please when you have a minute read the documentation and close this issue if you're satisfied :)

**Comment by wircho** [comment]
I've added support for notifications. Please when you have a minute read the documentation and close this issue if you're satisfied :)

**Comment by AndrewSB** [comment]
Looks awesome!
