### ISSUE TITLE
swift 3 support

### ISSUE THREAD

**Issue by FabianTerhorst** [wircho/Curly#6]
Is swift 3 support planned?

**Comment by wircho** [comment]
Yes! Added to my todo list. Probably this week.

**Comment by FabianTerhorst** [comment]
I also migrated a little to swift 3: https://github.com/FabianTerhorst/Curly/commit/9fcf85c5f62379efc1e9d54b5921f77958ef27c2 but its just a quick fix so that i can use my app with swift 3.

**Comment by vdka** [comment]
I had to make some further changes to get compilation going based off of @FabianTerhorst work.
https://gist.github.com/cb1eaabc491f0b1ac25054ba1fa1ff6b

**Comment by rsomlette** [comment]
Any updates?

**Comment by wircho** [comment]
@Niphery Doing this now.

**Comment by wircho** [comment]
I've done the Swift 3 update. Closing this issue.
